[package]
authors.workspace = true
description.workspace = true
edition.workspace = true
name = "probe"
repository.workspace = true
version.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap.workspace = true
color-eyre.workspace = true
probe-args.workspace = true
probe-ops.workspace = true

[features]
default = [ "rpc" ]
rpc = [  ]
