[workspace]
resolver = "2"
members = ["args", "cli", "rika"]

[workspace.package]
authors = ["Kari <evergreenkary@gmail.com>"]
description = "A Starknet toolkit."
edition = "2021"
repository = "https://github.com/kariy/rika-chan"
version = "0.1.2"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace.dependencies]
rika-args = { path = "args" }
rika = { path = "rika" }

async-trait = "0.1.60"
cairo-lang-starknet = "2.5.3"
chrono = "0.4.23"
clap = { version = "4.1.8", features = ["derive", "env"] }
clap_complete = "4.1.0"
comfy-table = "6.1.4"
crypto-bigint = "0.5.3"
dunce = "1.0.3"
eyre = "0.6.8"
hex = "0.4.3"
home = "0.5.4"
inquire = "0.6.2"
rand = "0.8.5"
reqwest = { version = "0.11.12", features = [
    "json",
    "rustls-tls",
], default-features = false }
serde = "1.0.145"
serde_json = "1.0.85"
shellexpand = "3.0.0"
starknet = "0.8.0"
starknet-keystore = { git = "https://github.com/kariy/starknet-keystore-rs" }
thiserror = "1.0.40"
tokio = { version = "1.24.2", features = ["full"] }
walkdir = "2.3.2"
