[package]
name = "starknet-cast"
description = "Perform RPC calls to the StarkNet network."
version = "0.1.1"
edition = "2021"
repository = "https://github.com/kariy/starknet-cast"

[[bin]]
name = "starknet-cast"
path = "./src/main.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "3.2.21", features = ["derive", "env"] }
eyre = "0.6.8"
hex = "0.4.3"
reqwest = "0.11.12"
serde = "1.0.145"
serde_json = "1.0.85"
starknet = { git = "https://github.com/xJonathanLEI/starknet-rs/" }
tokio = { version = "1.21.1", features = ["full"] }
