[package]
name = "starknet-probe"
description = "A cli tool for performing RPC calls to the StarkNet network."
authors = ["Kari <evergreenkary@gmail.com>"]
version = "0.1.1"
edition = "2021"
repository = "https://github.com/kariy/starknet-probe"

[[bin]]
name = "probe"
path = "./src/main.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "3.2.21", features = ["derive", "env"] }
crypto-bigint = "0.4.9"
eyre = "0.6.8"
hex = "0.4.3"
reqwest = "0.11.12"
serde = "1.0.145"
serde_json = "1.0.85"
starknet = { git = "https://github.com/xJonathanLEI/starknet-rs/" }
tokio = { version = "1.21.1", features = ["full"] }
