[package]
name = "starknet-cast"
description = "Like Foundry's but for StarkNet"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "starknet-cast"
path = "./src/main.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "3.2.21", features = ["derive"] }
hex = "0.4.3"
starknet-core = { git = "https://github.com/xJonathanLEI/starknet-rs/" }