name: ci

on:
    pull_request:
    push:
        branches:
            - main

jobs:
    test:
        name: "Test"
        runs-on: "ubuntu-latest"
        steps:
            - uses: "actions/checkout@v3"
            - uses: Swatinem/rust-cache@v2
            - uses: "actions-rs/toolchain@v1"
              with:
                  override: true
                  profile: "minimal"
                  toolchain: "stable"
            - run: |
                  "cargo install cargo-nextest"
                  "cargo nextest --all-features"

    fmt:
        name: "Formatting"
        runs-on: "ubuntu-latest"
        steps:
            - uses: "actions/checkout@v3"
            - uses: "actions-rs/toolchain@v1"
              with:
                  override: true
                  profile: "minimal"
                  toolchain: "nightly"
                  components: "rustfmt"
            - uses: "actions-rs/cargo@v1"
              with:
                  command: "fmt"
                  args: "--all"
            - run: |
                  "cargo install taplo-cli"
                  "taplo fmt"

    clippy:
        name: "Clippy"
        runs-on: "ubuntu-latest"
        steps:
            - uses: "actions/checkout@v3"
            - name: "Setup cmake"
              uses: "jwlawson/actions-setup-cmake@v1.13"
            - uses: "actions-rs/toolchain@v1"
              with:
                  override: true
                  profile: "minimal"
                  toolchain: "nightly"
                  components: "clippy"
            - uses: "actions-rs/cargo@v1"
              with:
                  command: "clippy"
                  args: "-- -D warnings"
